### ISSUE TITLE
On Raspberry PI playsound.py not work

### ISSUE THREAD

**Issue by tapirencrypt** [ZapdoZ/numberstations#4]
Hello theverygaming and ZapdoZ.

I need your help. Unfortunately, I cannot install your programme on my Raspberry PI. Can you help me?

Thank you.

```
pi@MORSE:~/Documents/numberstations $ uname -a
Linux MORSE 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
pi@MORSE:~/Documents/numberstations $ lsb_release -d
Description:	Debian GNU/Linux 11 (bullseye)
pi@MORSE:~/Documents/numberstations $ python -V
Python 3.9.2
pi@MORSE:~/Documents/numberstations $ 


pip install playsound
pip3 install playsound
pip install multiprocess
pip3 install multiprocess
pip install pygobject
pip3 install pygobject

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: playsound in /home/pi/.local/lib/python3.9/site-packages (1.3.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: playsound in /home/pi/.local/lib/python3.9/site-packages (1.3.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: multiprocess in /home/pi/.local/lib/python3.9/site-packages (0.70.12.2)
Requirement already satisfied: dill>=0.3.4 in /home/pi/.local/lib/python3.9/site-packages (from multiprocess) (0.3.4)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: multiprocess in /home/pi/.local/lib/python3.9/site-packages (0.70.12.2)
Requirement already satisfied: dill>=0.3.4 in /home/pi/.local/lib/python3.9/site-packages (from multiprocess) (0.3.4)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (3.38.0)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from pygobject) (1.16.2)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (3.38.0)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from pygobject) (1.16.2)

pi@MORSE:~/Documents/numberstations $ python interface.py 
playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
[Primary ID] Group 791 accepted
[Secondary ID] Group 228 accepted
[Group count] Group 2 accepted
---Begin Main group check---
Group #1 12345 Accepted
Group #2 98745 Accepted
[Primary ID] Group 791 accepted
[Secondary ID] Group 228 accepted
[Group count] Group 2 accepted
---Begin Main group check---
Group #1 12345 Accepted
Group #2 98745 Accepted
For ID 791
1 message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/playsound.py", line 261, in <module>
    playsound(argv[1])
  File "/home/pi/.local/lib/python3.9/site-packages/playsound.py", line 163, in _playsoundNix
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
Process Process-1:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/home/pi/.local/lib/python3.9/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Documents/numberstations/interface.py", line 493, in <lambda>
    mainstation = multiprocess.Process(target=lambda: initstation(station="G06",
  File "/home/pi/Documents/numberstations/interface.py", line 338, in initstation
    g06(kwargs.get("ID"), kwargs.get("secid"), kwargs.get("grpcnt"), kwargs.get("message"))
  File "/home/pi/Documents/numberstations/stations.py", line 148, in g06
    playsound("Stasi/de/{}.wav".format(activenumber))
  File "/home/pi/.local/lib/python3.9/site-packages/playsound.py", line 254, in <lambda>
    playsound = lambda sound, block = True: _playsoundAnotherPython('/usr/bin/python3', sound, block, macOS = False)
  File "/home/pi/.local/lib/python3.9/site-packages/playsound.py", line 229, in _playsoundAnotherPython
    t.join()
  File "/home/pi/.local/lib/python3.9/site-packages/playsound.py", line 218, in join
    raise self.exc
  File "/home/pi/.local/lib/python3.9/site-packages/playsound.py", line 211, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/playsound.py", line 226, in <lambda>
    t = PropogatingThread(target = lambda: check_call([otherPython, playsoundPath, _handlePathOSX(sound) if macOS else sound]))
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/pi/.local/lib/python3.9/site-packages/playsound.py', 'Stasi/de/7.wav']' returned non-zero exit status 1.
pi@MORSE:~/Documents/numberstations $ 
```

**Comment by tapirencrypt** [comment]
Forgotten, as I said, I don't get any audio output.
